name: MANUAL Build/release LINUX

# on:
#   push:
#     tags:
#       - "*"

on: workflow_dispatch
# on: push

jobs:
  release:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest]
        os: [ubuntu-latest]
        # os: [macos-latest, ubuntu-latest, windows-latest]
        # os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Build/release Electron Linux
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          build_script_name: "build:prod"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          # release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          release: true
